"""final pre-deploy

Revision ID: d87f86f23be5
Revises: c5e9abdd937f
Create Date: 2026-01-28 16:17:42.949887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd87f86f23be5'
down_revision: Union[str, Sequence[str], None] = 'c5e9abdd937f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'])
    op.alter_column('documents', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'source_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('escalations', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('escalations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'escalations', 'chat_sessions', ['session_id'], ['id'])
    op.alter_column('faqs', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('faqs', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faqs', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               nullable=True)
    op.alter_column('faqs', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_constraint(None, 'escalations', type_='foreignkey')
    op.alter_column('escalations', 'confidence',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('escalations', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('documents', 'source_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('documents', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.alter_column('document_chunks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('document_chunks', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
